# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Packet-Target
version:      1.00
version_from: lib/Net/Packet/Target.pm
installdirs:  site
requires:
    Class::Gomor:                  1.00
    Net::Packet:                   3.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
